### ISSUE TITLE
Fails to login if ~/.bashrc isn't writable on remote

### ISSUE THREAD

**Issue by puck** [grantm/bcvi#2]
If bcvi can't write to ~/.bashrc then the ssh connection aborts and you can't login.

**Comment by grantm** [comment]
I suspect the fact that you were unable to complete a login is only because you have your AutoInstall plugin installed - bcvi would not normally try to do an install when you just tried to log in.

I still want bcvi to exit with a non-zero status in the case where the --install option is used explicitly and the install fails.  However I've tweaked the install code so that now the install_to_host() method that your plugin calls will return true on success or false on failure (rather than dying).  This also required a change to my InstallManager plugin.  But the good news is if you update both of those, you shouldn't have to change any code in your plugin :-)

Changes released to CPAN in: 
- App-BCVI 3.08
- App-BCVI-InstallManager 1.03

**Comment by puck** [comment]
Excellent, that works much better.

Also, now bcvi --update-all will keep on running even if one of the
hosts isn't present.

Cheers!

On Fri, 2012-10-05 at 16:12 -0700, Grant McLean wrote:

> I suspect the fact that you were unable to complete a login is only
> because you have your AutoInstall plugin installed - bcvi would not
> normally try to do an install when you just tried to log in.
> 
> I still want bcvi to exit with a non-zero status in the case where the
> --install option is used explicitly and the install fails. However
> I've tweaked the install code so that now the install_to_host() method
> that your plugin calls will return true on success or false on failure
> (rather than dying). This also required a change to my InstallManager
> plugin. But the good news is if you update both of those, you
> shouldn't have to change any code in your plugin :-)
> 
> Changes released to CPAN in: 
> 
> ```
>   * App-BCVI 3.08
>   * App-BCVI-InstallManager 1.03
> ```
> 
> —
> Reply to this email directly or view it on GitHub. 

## 

Andrew Ruthven
Wellington, New Zealand
At home: andrew@etc.gen.nz |   linux.conf.au 2013
                           | Come join the party...
                           |  http://linux.conf.au
