### ISSUE TITLE
Compatibility with tcsh

### ISSUE THREAD

**Issue by aerorahul** [grantm/bcvi#4]
If the default login shell on the remote is tcsh, bcvi fails to create the appropriate aliases in .cshrc
Is there a hack to enable the use of bcvi with tcsh login shells?
The server we use has tcsh as the default shells on the client and server.
Any help would be greatly appreciated.

**Comment by grantm** [comment]
I can't say I've ever used any of the *csh shells.  I'd imagine there are two barriers:
- the --install process wants to install the $TERM unpacker and alias setup in .profile or similar
- the routine which outputs the aliases is doing it with the wrong syntax for a csh variant

You could manually edit the appropriate .*rc file on the target machine to unpack $TERM and set up the correct alias.  Given knowledge of the correct syntax, both of these things could be worked around with a bcvi plugin, but someone would need to write it :-)

The installer could possibly try to determine what shell the target machine is running, but even that behaviour would be best placed in a plugin since only people with 'exotic' shells would need to run it.

**Comment by aerorahul** [comment]
Grant,

Thank you for the response.

I was able to work it the existing bcvi. Instead of overloading the TERM
variable, I pass in only the BCVI_CONF details, and I assume that if it is
not xterm or xterm-254color, it is BCVI_CONF. I then set it accordingly in
my .cshrc

This is done because, when I log in to the server, the first thing that is
done is /etc/cshrc.login is sourced. It contains references to TERM
variable and thus the login fails to give the correct prompt and does not
source the necessary modules necessary for other things. By doing this
alternative, it simply ignores and sets the terminal as a "dumb" terminal
and continues with loading the modules and setting the system specific
paths.

I tried to look for variables other than TERM and prompt that can be
overloaded and which are not used in /etc/cshrc.login Do you have a
suggestion. The SendEnv and AcceptEnv cannot work, since AcceptEnv needs to
be configured in /etc/sshd_config on the server.

Thanks again.
Rahul.

**Comment by grantm** [comment]
As far as I know, TERM is the only variable forwarded by default.  You may be able to work around `/etc/cshrc.login` running first by running those commands again after unpacking $TERM
